#spring:
#  application:
#    name: Agent
#  profiles:
#    active: local
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:7b
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
##        stdio:
##          servers-configuration: classpath:mcp-servers.json
#
#  # 临时注释掉，便于大家开发调试和部署（实际填写 PgVector 数据库信息）
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#
#server:
#  port: 8123
#  servlet:
#    context-path: /api
#  # springdoc-openapi????
#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html
#      tags-sorter: alpha
#      operations-sorter: alpha
#    api-docs:
#      path: /v3/api-docs
#    group-configs:
#      - group: 'default'
#        paths-to-match: '/**'
#        packages-to-scan: com.funian.agent.controller
#  # knife4j???????????????
#  knife4j:
#    enable: true
#    setting:
#      language: zh_cn
#
#
##  logging:
##    level:
##      org.springframework.ai.chat.client.advisor.SpringAIClientAdvisor: debug
